<?php

/**
 * @file
 * Contains store_locator.module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\store_locator\Helper\GoogleApiKeyHelper;
use Drupal\file\Entity\File;

/**
 * Implements hook_help().
 */
function store_locator_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.store_locator') {
    $text = file_get_contents(__DIR__ . '/README.md');
    if (!Drupal::moduleHandler()->moduleExists('markdown')) {
      return '<pre>' . $text . '</pre>';
    }
    else {
      /** @var \Drupal\markdown\PluginManager\ParserManagerInterface $parser_manager */
      $parser_manager = \Drupal::service('plugin.manager.markdown.parser');
      $parser = $parser_manager->getDefaultParser([
        'render_strategy' => ['type' => 'none'],
      ]);
      return $parser->parse($text);
    }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 */
function store_locator_theme($existing, $type, $theme, $path) {
  return [
    'location_data' => [
      'variables' => ['location_search' => NULL],
      'file' => 'store_locator.theme.inc',
    ],
  ];
}

/**
 * Implements hook_entity_view_alter().
 */
function store_locator_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->getEntityTypeId() == 'store_locator' && $build['#view_mode'] == 'full' && !empty($build['name']['#object'])) {
    $fid = \Drupal::config('store_locator.settings')->get('marker');
    $icon_url = '';
    if (!empty($fid)) {
      $file_entity = File::load($fid);
      $icon_url = \Drupal::service('file_url_generator')->generateAbsoluteString($file_entity->getFileUri());
    }
    $lat = $build['name']['#object']->get('latitude')->value;
    $lng = $build['name']['#object']->get('longitude')->value;
    $lat_lng = ['lat' => (float) $lat, 'lng' => (float) $lng];
    $build['#attached']['drupalSettings']['store_locator']['latlng'] = $lat_lng;
    $build['#attached']['drupalSettings']['store_locator']['icon'] = $icon_url;
    $build['map']['#markup'] = '<div id="map" class="loc-map store-locator-page-view"></div>';
    $build['map']['#weight'] = 100;
    $build['#attached']['library'][] = 'store_locator/store_locator.page';
    $googleMapKey = GoogleApiKeyHelper::getGoogleApiKey();
    $build['#attached']['html_head'][] = [$googleMapKey, 'googleMapKey'];
  }
}
